---
title: "In-class Exercise 5 - Visual Analytics for Building Better Explanatory Models"
author: "Shreya Agarwal"
date: "February 15, 2025"
date-modified: "last-modified"
execute: 
  echo: true
  eval: true
  warning: false
  message: false
  freeze: true
---

# **1. Getting Started**

## **1.1 Installing and loading the packages**

```{r}
pacman::p_load(tidyverse, readxl, SmartEDA, 
               easystats, gtsummary, ggstatsplot)
```

## **1.2 Importing the data**

```{r}
car_resale <- read_xls("data/ToyotaCorolla.xls", "data")
```

```{r}
glimpse(car_resale)
```

```{r}
list(car_resale)
```

```{r}
summary(car_resale)
```

# **2. Data Overview**

```{r}
summary1 <- car_resale %>%
  ExpData(type = 1)
```

```{r}
summary1
```

```{r}
car_resale %>%
  ExpData(type = 2)
```

```{r}
cols <- c("Mfg_Month", "HP_Bin", "CC_bin", "Doors", "Gears", 
          "Cylinders", "Fuel_Type", "Color", 
          "Met_Color" , "Automatic", "Mfr_Guarantee", "BOVAG_Guarantee", 
          "ABS", "Airbag_1", "Airbag_2", "Airco", "Automatic_airco", 
          "Boardcomputer", "CD_Player", "Central_Lock", "Powered_Windows", 
          "Power_Steering", "Radio", "Mistlamps", "Sport_Model", "Backseat_Divider", "Metallic_Rim", "Radio_cassette", "Tow_Bar")

car_resale <- car_resale %>%
  mutate(Id = as.character(Id)) %>%
  mutate_each_(funs(factor(.)), cols)
```

# **3. Plotting Visualizations**

```{r}
car_resale %>%
  ExpNumViz(target = NULL,
            nlim = 10,
            Page = c(2,2))
```

```{r}
car_resale %>%
  ExpNumViz(target = "Price",
            nlim = 10,
            Page = c(2,2))
```

### Bar plots for all categorical variables

```{r}
#| fig-width: 12
#| fig-height: 10

car_resale %>%
  ExpCatViz(target = NULL,
            col = "sky blue",
            clim = 10,
            margin = 2,
            Page = c(4,4),
            sample = 16)

```

```{r}
car_resale %>%
  ExpNumViz(target = "Price",
            scatter = FALSE,
            fname = NULL,
            col = "green")
```

```{r}
model <- lm(Price ~ Age_08_04 + Mfg_Year + KM + 
              Weight + Guarantee_Period, data = car_resale)

model
```

```{r}
check_collinearity(model)
```

```{r}
check_c  <- check_collinearity(model)
plot(check_c)
```

```{r}
model1 <- lm(Price ~ Age_08_04 + KM + 
              Weight + Guarantee_Period, data = car_resale)

check_normality(model1)
```

```{r}
check_heteroscedasticity(model1)
```

```{r}
check_model(model1)
```

```{r}
summary(model1)
```

```{r}
tbl_regression(model1,
               intercept = TRUE)
```

```{r}
tbl_regression(model1,
               intercept = TRUE) %>%
  add_glance_source_note(
    label = list(sigma ~ "\U03C3"),
    include = c(r.squared, adj.r.squared,
                AIC, statistic,
                p.value, sigma)
  )
```

```{r}
p_model1 <- (parameters(model1))
```

```{r}
plot(parameters(model1))
```

```{r}
ggcoefstats(model1, 
            output = "plot")
```
